version: "3"

services:
  web:
    image: nginx:1.17-alpine
    container_name: i_web1
    depends_on:
      - app
    ports:
      - 10080:80
    environment:
      - TZ=${TZ}
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-app:/workspace
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    container_name: i_app1
    working_dir: /workspace
    environment:
      - TZ=${TZ}
    volumes:
      - ./docker/ash:/etc/profile.d
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./laravel-app:/workspace
      - ./docker/php/psysh:/root/.config/psysh
  db:
    image: mysql:8.0
    container_name: i_db1
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  node:
    image: node:12.14-alpine
    tty: true
    volumes:
      - ./laravel-app:/workspace
    working_dir: /workspace
